# -*- coding: utf-8 -*-
# ITU prefix -> ISO-2 -> emoji flag

_RANGES = """
AAA-ALZ:US AMA-AOZ:ES APA-ASZ:PK ATA-AWZ:IN AXA-AXZ:AU AYA-AZZ:AR
A2A-A2Z:BW A3A-A3Z:TO A4A-A4Z:OM A5A-A5Z:BT A6A-A6Z:AE A7A-A7Z:QA
A8A-A8Z:LR A9A-A9Z:BH BAA-BZZ:CN CAA-CEZ:CL CFA-CKZ:CA CLA-CMZ:CU
CNA-CNZ:MA COA-COZ:CU CPA-CPZ:BO CQA-CUZ:PT CVA-CXZ:UY CYA-CZZ:CA
C2A-C2Z:NR C3A-C3Z:AD C4A-C4Z:CY C5A-C5Z:GM C6A-C6Z:BS C8A-C9Z:MZ
DAA-DRZ:DE DSA-DTZ:KR DUA-DZZ:PH D2A-D3Z:AO D4A-D4Z:CV D5A-D5Z:LR
D6A-D6Z:KM D7A-D9Z:KR EAA-EHZ:ES EIA-EJZ:IE EKA-EKZ:AM ELA-ELZ:LR
EMA-EOZ:UA EPA-EQZ:IR ERA-ERZ:MD ESA-ESZ:EE ETA-ETZ:ET EUA-EWZ:BY
EXA-EXZ:KG EYA-EYZ:TJ EZA-EZZ:TM E2A-E2Z:TH E3A-E3Z:ER E4A-E4Z:PS
E5A-E5Z:CK E6A-E6Z:NU E7A-E7Z:BA FAA-FZZ:FR GAA-GZZ:GB HAA-HAZ:HU
HBA-HBZ:CH HCA-HDZ:EC HEA-HEZ:CH HFA-HFZ:PL HGA-HGZ:HU HHA-HHZ:HT
HIA-HIZ:DO HJA-HKZ:CO HLA-HLZ:KR HMA-HMZ:KP HNA-HNZ:IQ HOA-HPZ:PA
HQA-HRZ:HN HSA-HSZ:TH HTA-HTZ:NI HUA-HUZ:SV HVA-HVZ:VA HWA-HYZ:FR
HZA-HZZ:SA H2A-H2Z:CY H3A-H3Z:PA H4A-H4Z:SB H6A-H7Z:NI H8A-H9Z:PA
IAA-IZZ:IT JAA-JSZ:JP JTA-JVZ:MN JWA-JXZ:NO JYA-JYZ:JO JZA-JZZ:ID
J2A-J2Z:DJ J3A-J3Z:GD J4A-J4Z:GR J5A-J5Z:GW J6A-J6Z:LC J7A-J7Z:DM
J8A-J8Z:VC KAA-KZZ:US LAA-LNZ:NO LOA-LWZ:AR LXA-LXZ:LU LYA-LYZ:LT
LZA-LZZ:BG L2A-L9Z:AR MAA-MZZ:GB NAA-NZZ:US OAA-OCZ:PE ODA-ODZ:LB
OEA-OEZ:AT OFA-OJZ:FI OKA-OLZ:CZ OMA-OMZ:SK ONA-OTZ:BE OUA-OZZ:DK
PAA-PIZ:NL PJA-PJZ:CW PKA-POZ:ID PPA-PYZ:BR PZA-PZZ:SR P2A-P2Z:PG
P3A-P3Z:CY P4A-P4Z:AW P5A-P9Z:KP RAA-RZZ:RU SAA-SMZ:SE SNA-SRZ:PL
SSA-SSM:EG SSN-STZ:SD SUA-SUZ:EG SVA-SZZ:GR S2A-S3Z:BD S5A-S5Z:SI
S6A-S6Z:SG S7A-S7Z:SC S8A-S8Z:ZA S9A-S9Z:ST TAA-TCZ:TR TDA-TDZ:GT
TEA-TEZ:CR TFA-TFZ:IS TGA-TGZ:GT THA-THZ:FR TIA-TIZ:CR TJA-TJZ:CM
TKA-TKZ:FR TLA-TLZ:CF TMA-TMZ:FR TNA-TNZ:CG TOA-TQZ:FR TRA-TRZ:GA
TSA-TSZ:TN TTA-TTZ:TD TUA-TUZ:CI TVA-TXZ:FR TYA-TYZ:BJ TZA-TZZ:ML
T2A-T2Z:TV T3A-T3Z:KI T4A-T4Z:CU T5A-T5Z:SO T6A-T6Z:AF T7A-T7Z:SM
T8A-T8Z:PW UAA-UIZ:RU UJA-UMZ:UZ UNA-UQZ:KZ URA-UZZ:UA VAA-VGZ:CA
VHA-VNZ:AU VOA-VOZ:CA VPA-VQZ:GB VRA-VRZ:HK VSA-VSZ:GB VTA-VWZ:IN
VXA-VYZ:CA VZA-VZZ:AU V2A-V2Z:AG V3A-V3Z:BZ V4A-V4Z:KN V5A-V5Z:NA
V6A-V6Z:FM V7A-V7Z:MH V8A-V8Z:BN WAA-WZZ:US XAA-XIZ:MX XJA-XOZ:CA
XPA-XPZ:DK XQA-XRZ:CL XSA-XSZ:CN XTA-XTZ:BF XUA-XUZ:KH XVA-XVZ:VN
XWA-XWZ:LA XXA-XXZ:MO XYA-XZZ:MM YAA-YAZ:AF YBA-YHZ:ID YIA-YIZ:IQ
YJA-YJZ:VU YKA-YKZ:SY YLA-YLZ:LV YMA-YMZ:TR YNA-YNZ:NI YOA-YRZ:RO
YSA-YSZ:SV YTA-YUZ:RS YVA-YYZ:VE YZA-YZZ:RS Y2A-Y9Z:DE ZAA-ZAZ:AL
ZBA-ZJZ:GB ZKA-ZMZ:NZ ZNA-ZOZ:GB ZPA-ZPZ:PY ZQA-ZQZ:GB ZRA-ZUZ:ZA
ZVA-ZZZ:BR Z2A-Z2Z:ZW Z3A-Z3Z:MK Z8A-Z8Z:SS 2AA-2ZZ:GB 3AA-3AZ:MC
3BA-3BZ:MU 3CA-3CZ:GQ 3DA-3DM:SZ 3DN-3DZ:FJ 3EA-3FZ:PA 3GA-3GZ:CL
3HA-3UZ:CN 3VA-3VZ:TN 3WA-3WZ:VN 3XA-3XZ:GN 3YA-3YZ:NO 3ZA-3ZZ:PL
4AA-4CZ:MX 4DA-4IZ:PH 4JA-4KZ:AZ 4LA-4LZ:GE 4MA-4MZ:VE 4OA-4OZ:ME
4PA-4SZ:LK 4TA-4TZ:PE 4VA-4VZ:HT 4WA-4WZ:TL 4XA-4XZ:IL 4ZA-4ZZ:IL
5AA-5AZ:LY 5BA-5BZ:CY 5CA-5GZ:MA 5HA-5IZ:TZ 5JA-5KZ:CO 5LA-5MZ:LR
5NA-5OZ:NG 5PA-5QZ:DK 5RA-5SZ:MG 5TA-5TZ:MR 5UA-5UZ:NE 5VA-5VZ:TG
5WA-5WZ:WS 5XA-5XZ:UG 5YA-5ZZ:KE 6AA-6BZ:EG 6CA-6CZ:SY 6DA-6JZ:MX
6KA-6NZ:KR 6OA-6OZ:SO 6PA-6SZ:PK 6TA-6UZ:SD 6VA-6WZ:SN 6YA-6YZ:JM
6ZA-6ZZ:LR 7AA-7IZ:ID 7JA-7NZ:JP 7OA-7OZ:YE 7PA-7PZ:LS 7QA-7QZ:MW
7RA-7RZ:DZ 7SA-7SZ:SE 7TA-7YZ:DZ 7ZA-7ZZ:SA 8AA-8IZ:ID 8JA-8NZ:JP
8OA-8OZ:BW 8PA-8PZ:BB 8QA-8QZ:MV 8RA-8RZ:GY 8SA-8SZ:SE 8TA-8YZ:IN
8ZA-8ZZ:SA 9AA-9AZ:HR 9BA-9DZ:IR 9EA-9FZ:ET 9GA-9GZ:GH 9HA-9HZ:MT
9IA-9JZ:ZM 9KA-9KZ:KW 9LA-9LZ:SL 9MA-9MZ:MY 9NA-9NZ:NP 9OA-9TZ:CD
9UA-9UZ:BI 9VA-9VZ:SG 9WA-9WZ:MY 9XA-9XZ:RW 9YA-9ZZ:TT
"""

_ALPHA = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
_P1 = {}
_P2 = {}
_P3 = {}

def _expand():
    for tok in _RANGES.split():
        rng, iso = tok.split(":")
        start, end = rng.split("-")
        if start[:2] == end[:2]:
            if start[2] == "A" and end[2] == "Z":
                _P2[start[:2]] = iso
            else:
                i = _ALPHA.index(start[2]); j = _ALPHA.index(end[2])
                for k in range(i, j + 1):
                    _P3[start[:2] + _ALPHA[k]] = iso
        else:
            i = _ALPHA.index(start[1]); j = _ALPHA.index(end[1])
            for k in range(i, j + 1):
                _P2[start[0] + _ALPHA[k]] = iso
            if start[1] == "A" and end[1] == "Z":
                _P1[start[0]] = iso

_expand()
_P3["3D2"] = "FJ"
_P3["3DA"] = "SZ"

def call_to_iso(cs):
    try:
        cs = str(cs).strip().upper()
        if not cs:
            return ""
        if "/" in cs:
            parts = [p for p in cs.split("/") if p]
            cand = None
            for p in parts:
                if any(ch.isdigit() for ch in p):
                    if cand is None or len(p) > len(cand):
                        cand = p
            cs = cand or parts[0]
        cs = "".join(ch for ch in cs if ch.isalnum())
        if len(cs) < 2:
            return ""
        if cs[:3] in _P3:
            return _P3[cs[:3]]
        if cs[:2] in _P2:
            return _P2[cs[:2]]
        return _P1.get(cs[0], "")
    except Exception:
        return ""

def call_flag(cs):
    iso = call_to_iso(cs)
    if len(iso) != 2 or not iso.isalpha():
        return ""
    return chr(0x1F1E6 + ord(iso[0]) - 65) + chr(0x1F1E6 + ord(iso[1]) - 65)
